# Generated by Django 4.0.1 on 2022-01-18 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id_service', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField(default=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id_worker', models.IntegerField(primary_key=True, serialize=False)),
                ('Full_name', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=30)),
                ('position', models.CharField(default='Грузчик', max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=14, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='operator',
            fields=[
                ('id_operator', models.IntegerField(primary_key=True, serialize=False)),
                ('Full_name', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=30)),
                ('position', models.CharField(default='Оператор', max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=14, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id_client', models.IntegerField(primary_key=True, serialize=False)),
                ('Full_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('Card_number', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
