# Generated by Django 4.0.1 on 2022-01-19 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogistic_v2', '0002_order_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_operator',
            field=models.ForeignKey(default=44, on_delete=django.db.models.deletion.CASCADE, to='Blogistic_v2.operator'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_worker',
            field=models.ForeignKey(default=51, on_delete=django.db.models.deletion.CASCADE, to='Blogistic_v2.worker'),
        ),
        migrations.CreateModel(
            name='Car_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogistic_v2.car')),
                ('number_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogistic_v2.order')),
            ],
        ),
        migrations.CreateModel(
            name='additional_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogistic_v2.order')),
                ('number_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogistic_v2.service')),
            ],
        ),
    ]
